app:
    resource: "@AppBundle/Controller/"
    type:     annotation
category:
    path:      /category
    defaults:  { _controller: AppBundle:Category:allCategory }
lead:
    path:      /lead
    defaults:  { _controller: AppBundle:Lead:allLead }
product:
    path:      /product
    defaults:  { _controller: AppBundle:Product:allCategory }