# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    category.business:
        class: AppBundle\Business\CategoryBusiness
        arguments: ["@doctrine.orm.entity_manager"]
    lead.business:
            class: AppBundle\Business\LeadBusiness
            arguments: ["@doctrine.orm.entity_manager"]
    product.business:
            class: AppBundle\Business\ProductBusiness
            arguments: ["@doctrine.orm.entity_manager"]
    order.business:
            class: AppBundle\Business\ProductOrderBusiness
            arguments: ["@doctrine.orm.entity_manager"]
    promotion.business:
            class: AppBundle\Business\PromotionBusiness
            arguments: ["@doctrine.orm.entity_manager"]
